[7X] Skip the foreign key constraint validation. (#14344)
Currently, Greenplum doesn't support foreign key constraint validation.
However, we only emit a warning message saying Greenplum doesn't support
it without skipping the validation process. I noticed this issue when I
was running the following query:

CREATE TABLE fk_test_reference (col2 text unique not null);
INSERT INTO fk_test_reference VALUES ('stuff');
CREATE UNLOGGED TABLE id_taptest_table (
    col1 bigint,
    col2 text not null default 'stuff',
    col3 timestamptz DEFAULT now(),
    col4 text,
    FOREIGN KEY (col2) REFERENCES fk_test_reference(col2))
  PARTITION BY RANGE (col1);
CREATE TABLE id_taptest_table_p3000000000 (
    LIKE id_taptest_table
    INCLUDING DEFAULTS
    INCLUDING CONSTRAINTS
    INCLUDING STORAGE
    INCLUDING COMMENTS
    INCLUDING GENERATED
    INCLUDING INDEXES);
ALTER TABLE id_taptest_table ATTACH PARTITION
    id_taptest_table_p3000000000 FOR VALUES FROM (3000000000) TO (3000000010);

There're 2 possible failures when attaching the newly created
partitioned table.

1. Greenplum emits an error message:
   ERROR:  XX000: no pre-assigned OID for pg_constraint tuple "id_taptest_table_col2_fkey" (namespace:0 keyOid1:16472 keyOid2:102) (oid_dispatch.c:374)  (seg2 127.0.0.1:7004 pid=195321) (oid_dispatch.c:374)
   LOCATION:  GetNewOrPreassignedOid, oid_dispatch.c:374

2. Greenplum emits an error message:
   ERROR:  0A000: function cannot execute on a QE slice because it accesses relation "public.id_taptest_table_p3000000000"  (seg2 127.0.0.1:7004 pid=108395)
   CONTEXT:  SQL statement "SELECT fk."col2" FROM ONLY "public"."id_taptest_table_p3000000000" fk LEFT OUTER JOIN ONLY "public"."fk_test_reference" pk ON ( pk."col2" OPERATOR(pg_catalog.=) fk."col2") WHERE pk."col2" IS NULL AND (fk."col2" IS NOT NULL)"
   LOCATION:  querytree_safe_for_qe_walker, functions.c:238

The root cause analysis:

When attaching a partitioned table with foreign key references,
Greenplum will check the constraints by running the query both on the
coordinator and on segments:

SELECT fk."col2" FROM ONLY "public"."id_taptest_table_p3000000000" fk
    LEFT OUTER JOIN ONLY "public"."fk_test_reference" pk
    ON ( pk."col2" OPERATOR(pg_catalog.=) fk."col2")
  WHERE pk."col2" IS NULL AND (fk."col2" IS NOT NULL)

If the check get passed, coordinator will dispatch the real command for
'ALTER TABLE ... ATTACH PARTITION ...' to segments. When performing the
'ALTER TABLE' command, coordinator needs to generate an OID for the
pg_constraint tuple 'id_taptest_table_col2_fkey' to keep the catalog
table consistent across the cluster. The dispatched OID will be cleaned
up if that transaction is aborted or committed.

The 1st possible failure occurs if we execute the 'ALTER TABLE' command
directly, the dispatched OID for altering table get cleaned up after the
constraint checking query finishing (the constraint checking query
executed in function 'RI_Initial_Check').

The 2nd possible failure occurs if we execute the 'ALTER TABLE' command
in a transaction block. The constraint checking query on coordinator
will success and coordinator will dispatch the real 'ALTER TABLE'
command to segments. The segment will also run the constraint checking
query but in QE mode (Gp_role == GP_ROLE_EXECUTE), so the query cannot
be executed because it's accessing some relation.

Anyway, Greenplum doesn't support foreign key constraints validation,
the simplest fixing is skipping the validation.

Fix #14279

(cherry picked from commit e1d4b817d9eb0537a3ec84499624124d1d091e79)