fix compiler warning for gcc-12. (#15813)
With gcc version 12.2.1 (Gentoo 12.2.1_p20230428-r1 p2), pgbench fails to
compile with following error:
commit 7cc8a58b865d96dad7e0b310ba72134de50f1152 introduced this 
flag in GPDB, and when using optimization level "O3" (as in GPDB) , 
this flag can cause compilation failures with the gcc-12 compiler.

```
In function 'coerceToInt',
    inlined from 'evalStandardFunc' at pgbench.c:2246:11:
pgbench.c:1667:17: error: 'vargs[0].type' may be used uninitialized [-Werror=maybe-uninitialized]
 1667 |         if (pval->type == PGBT_INT)
      |             ~~~~^~~~~~
pgbench.c: In function 'evalStandardFunc':
pgbench.c:1875:22: note: 'vargs' declared here
 1875 |         PgBenchValue vargs[MAX_FARGS];
      |                      ^~~~~
In function 'coerceToInt',
    inlined from 'evalStandardFunc' at pgbench.c:2246:11:
pgbench.c:1669:32: error: 'vargs[0].u.ival' may be used uninitialized [-Werror=maybe-uninitialized]
 1669 |                 *ival = pval->u.ival;
      |                         ~~~~~~~^~~~~
pgbench.c: In function 'evalStandardFunc':
pgbench.c:1875:22: note: 'vargs' declared here
 1875 |         PgBenchValue vargs[MAX_FARGS];
      |                      ^~~~~
In function 'coerceToInt',
    inlined from 'evalStandardFunc' at pgbench.c:2246:11:
pgbench.c:1674:40: error: 'vargs[0].u.dval' may be used uninitialized [-Werror=maybe-uninitialized]
 1674 |                 double          dval = rint(pval->u.dval);
      |                                        ^~~~~~~~~~~~~~~~~~
pgbench.c: In function 'evalStandardFunc':
pgbench.c:1875:22: note: 'vargs' declared here
 1875 |         PgBenchValue vargs[MAX_FARGS];
      |                      ^~~~~
```