Fix incorrect codes in pg_backup_archiver.c (#899)
pg_backup_archiver.c: In function ‘CloneArchive’:
pg_backup_archiver.c:4877:9: error: the comparison will always evaluate as ‘true’ for the address of ‘binary_upgrade’ will never be NULL [-Werror=address]
 4877 |         ConnectDatabase((Archive *) clone, &clone->public.ropt->cparams, true, &clone->public.ropt->binary_upgrade);
      |         ^~~~~~~~~~~~~~~
In file included from pg_backup_archiver.h:30,
                 from parallel.h:19,
                 from pg_backup_archiver.c:39:
pg_backup.h:138:33: note: ‘binary_upgrade’ declared here
  138 |         int                     binary_upgrade;
      |                                 ^~~~~~~~~~~~~~

(cherry picked from commit 4b71649a539f52425b4b2aca75d961c1720761d4)