Suppress unused function warn when configure with --disable-orca (#951)
To fix:

In file included from pg_hint_plan.c:34:
../../src/include/optimizer/orca.h:30:1: error: ‘optimize_query’ defined but not used [-Werror=unused-function]
   30 | optimize_query(Query *parse, int cursorOptions, ParamListInfo boundParams)
      | ^~~~~~~~~~~~~~
make[2]: Leaving directory '/home/reshke/cloudberrydb/gpcontrib/gp_inject_fault'

(cherry picked from commit f24f5169d57755b95b0db704195a7d6d52ddb07d)