fix GPDB_96_MERGE_FIXME, do not need to check forceDistRandom in set_cte_pathlist (#15527)
fix GPDB_96_MERGE_FIXME: Should we check forceDistRandom here, like set_subquery_pathlist() does? 
```
create table ttt(tc1 int,tc2 int) ;
insert into ttt values(1,1);
insert into ttt  values(2,2);

WITH cte AS (
  SELECT oid, relname
  FROM pg_class
  WHERE oid <2000
)
SELECT *
FROM gp_dist_random('cte')
JOIN ttt ON cte.oid = ttt.tc2;
 
ERROR:  relation "cte1" does not exist
```
CET can not be the param of gp_dist_random.
So in set_cte_pathlist we do not need to check forceDistRandom.
Remove GPDB_96_MERGE_FIXME in allpaths.c

(cherry picked from commit f4a9a6f6bea70365fcb259492493646d626edd0c)