Io limit improve error log (#16394)
When io_limit encountered syntax error, previous log is just
"Error: Syntax error".

Now, the io_limit has comprehensive log for syntax error:

```
demo=# create resource group rg1 WITH (cpu_max_percent=10,
                                       io_limit='pg_defaultrbps=100,
                                       wbps=550,riops=1000,wiops=1000');
ERROR:  io limit: syntax error, unexpected '=', expecting ':'
HINT:   pg_defaultrbps=100, wbps=550,riops=1000,wiops=1000
                      ^
```

```
demo=# create resource group rg1 WITH (cpu_max_percent=10,
                                       io_limit='pg_default:
                                       rbps=100wbps=550,riops=1000,
                                       wiops=1000');
ERROR:  io limit: syntax error, unexpected IO_KEY, expecting end of file or ';'
HINT:   pg_default:rbps=100wbps=550,riops=1000,wiops=1000
                           ^
```

(cherry picked from commit 60802217fa0d211d5d77a3a4a809c2cca5934420)